language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.4"
  - "5.11"
  - "6.1"

script: ./travis-test.sh

branches:
  except:
    - gh-pages

#after_script:
#  - if [[ `node --version` == *v0.12* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
